# Generated by Django 3.1.5 on 2021-01-27 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_contact_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phno',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_phno',
            field=models.IntegerField(),
        ),
    ]
