# Generated by Django 3.1.5 on 2021-01-27 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210127_1736'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='msg',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_psw',
            new_name='user_password',
        ),
        migrations.AlterField(
            model_name='contact',
            name='phno',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_phno',
            field=models.BigIntegerField(),
        ),
    ]
